---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-config-v1
  namespace: media
# labels:
  # snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block
# storageClassName: synology-iscsi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-serverdata-v1
  namespace: media
# labels:
  # snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block
# storageClassName: synology-iscsi
