---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tdarr-gatus-ep
  namespace: organizers
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: Tdarr
        group: Media
        url: https://tdarr.bharris.vip
        interval: 1m
        client:
          dns-resolver: tcp://10.0.111.20:53
        conditions:
          - "[STATUS] == 200"
