---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: ghcr.io/sct/overseerr
      tag: 1.33.2

    env:
      LOG_LEVEL: "info"
      PORT: 80

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: mdi:eye-circle
#         cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host "overseerr.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
#          secretName: "overseerr-tls"

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch

    persistence:
      config:
        enabled: true
        existingClaim: overseerr-config-v1
        mountPath: /app/config

    resources:
      requests:
        cpu: 15m
        memory: 226M
      limits:
        memory: 1937M
