# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: kube-system
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:6Ex7V/LhskKeLBmbyZl3SElyKIM5v1Mtypa1cFOuX4LWQaMmdi0Bugfndj5N+iAAhiIy3kuH2qrNgNXcMn3lGbUBAXBGN0F5mYi3YNFzfXa7iE1UxMfjjgUJt3cYlHqhvwsxae6d2cmwO0MpV0U59m4OHw08KBIL2Krocjx3RFji4rvzE4lCnDjawcamKsapPvPcAZ26Tm2pSwl0yW0+RqR6VwaD/D/9D8SWkzuWWj+WzrrMfLAvXZzFTtDBtobsQyaAoAVulc7+TY0h/8tDEApfcSt4QMJQh5O8z44/vVkPAEjsaXwXwAF3aDIFTD3Pcej/G+k0dhAnWrDS4tmkp2YIc1PCYBOXPFBu2zzMb80XYq1D6K1M+RDyMLnGLgcQGXOOMkbvOMislwRMUIoyu16pOl4Tj3iu/fdC6timkLq1WN5tFCQqKiZsL5J2OaDD60TXZuEXFLqcJNA9mCcCwS3BpigeEgtRw5kaAC7wnt4vvjoHwTOUz/ZwRlDFLRWzPZ45EWzUwXqRIrHyv+RS0jP2yq3eKNX8pN/2ucdh3B9gDOryZELAz11bTCI3B56IKPWvnOxAqDJn2s5RF876YPd0MItSKPm7ouHeN+lYztoJLj6o6c7+7FtUTGpftBNVl0qJSwI5i21wYL5JYSZboiUrxjh8MzxU+tvJrk+6CY2A1yhXzvWq68Y4WUdPqEH3Uwqan3mBphb97z2grxIyWbBg9y/aku7TYS+xlvc4vG5Qmx64J+VjoEAQvMtPLnPsn35VzIZvCs2nj5TOYXJabvW+MuqvCp7gASrkWvh0c0fYWiCIMjKFNKroMiKAi3I91lu4Ekz0hdfu5xs1q2E4MZD1b827/qoGkvpkubqdYEs4Ys9LXjtYiU4ZXSogF28TdJoti8uX4gPhGjWnQhl/MMdu4JhdGGg95V7LHQI/hmdo5m8x4Ay1J3qyTEK66hu1aS24jk098qMmLpR0sXfEWCRbFxTdS40qSOjQXgvdJSwUNIE8qCQUIUr7MpwJbX2NIujPnyuEtFn6867CsNL01nIJjo0q6592gHM7xhhjHzSKf3/tbVHuN7dXMjJKMRO8hBO0MDZNeXlF00kdzjfM6NN8CD4+BCttlADJOwzBOlZVz/HY+05/gm1i11hMUDzZ/x0dxOjhBnjQGCa/C5U3gW/emSJjvnE0dzgeZD75tOzvOGv/f74QU9xDP0xLgIFczCPBfiWdvWY5c0M+x6MPxWY0RroTuh7h5V9RAHrJ0I/gQC0l15zGIg/Qi7gDUSTZO7GQ+y+zv0mcbhFEK15s0HDRu72hprOVFUdFaU7gytFrJ9UMaa/wO8IzD9ZbJy9QJc35Y1WmWml/H00z4jk5VLn2xvOIH6FRXcakj/HHSIXGDDFDA35ZzuO83Fa+024MlDyPldMcLw9hE8UMpxJ6jVdJf4y1jXV7/1gh6YmAxuJ577wTPg2ZM6mlXAmcaEO9i+3nlOZWhs0r2wQSHhoPaeK5LfLoK2521KA1k/aUq/TBnh1E4SU9elqnZ1GVtoXIte4SVCtLfduJ2NR2IG/Rl7UDxzuMyrqY8JV8FKdck0cZMW1/Faij3+SyhC2Fi87BAYGpFkq2H8ULUCeJVCSmo7GcjlWYLT1wvPZI9OPNPQBmhxAHk9RzRkdEKJEvFdU3EEjdELCRftv6OLwu4UscfNTbUKS5bqNs/A2OAuCfBIgdAvkrAMm2cGvcmkILXve+a0tcPXw3zmKwxa6fGT0gytH1zpqCD1eZvi3nm+DxzTUVRWdcKQqRHSg7JpR66oJuUhHp0g8c1COjcvMF5r1Ju+O+RqLdnhOMm5hh6xOFFZwU8HcfG/49Wyl+wFU8j4M2mWjNl/BYxFCTi0ZJgmbXG6QQPF6AznvsGJO0wgSInUdU/XcEF8csperQuYDA0ovXLtMLt+SkVuqQprU=,iv:0zyqYaXWPowEb20TCsdsteEYf0gYaodxkrWlBjT9Bwg=,tag:/cjOrN6mrvyC/0uBE2PXQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWTA4a0NWMnZueEU5VE5M
            dEdsR1drV2RYQWlVWE9qU0xMRUMzV3lEaG40CkZnQUExSkVpOU1hVlIyUW5VMDRO
            K0hpQnN1VkpkajZlMmhjU3ZwYktRWDgKLS0tIGFBa0FrMU15N1NKQkpRVlJKUHY3
            WU11bllTR1Nudkx5UTJlODBwS1krRkUKOYC26vnIllLO8ndx9jV8SvhnEa1C37Ec
            XxNfd33EN48ARKe/B3qz1df+6fF9EW/Lu5tpr5XZ8D5MEze7+oeMTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-09T00:25:12Z"
    mac: ENC[AES256_GCM,data:h+s0wx8BD/ZsJbZQehFcZauIXGN3/V9UjOMhh6Qg94z21jbamkswlrz6wesstPtQsOC94xXpKF3Ae1ibXyAidkfyZB0qJPF6iBeOOyD5vmXRK7SuCFPpz/DSWiIxwO7N2k1D3NjiJg9SsoKd17KNFUZMfT8KsZZ1PGWjgJj+m6g=,iv:d+MbASTlZLvg0tLPW+pbsyJVL8KlQ5vLzt+khrNApyY=,tag:5NJgJc69Fp3+RGFTLyQz4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
---
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: kube-system
stringData:
    token: ENC[AES256_GCM,data:BStZG995kALwpE+58juosrb0enuXJXzYcz5mmeMWQ9WnzzxoPLY/syFl+hkXJsDvhG+jMtKU9nzUe7iUHtrT6oSttPvpevH2EQbkm2nAPw+Rqs/hENhen2jZdTxnpWqFFMGzi9agiFK41BtB0H5UccwAuW6ASqJ7Aor+kI00eHtSArfIz+5i1dadD4KFdncgkoPObmxm2HXQl0Pa4CqgmLlOaSeRhHZ56jUJ3S26HuQjPLVnL5VsaTmHeJyz3ELk030YAjai/FvXkdW2SrA4abiEJyN+cgo3UQrcXopn7KuDLTVnzVhMxxNdvxgyWuCzLEMa2Poxb/dFh6Eq0f+MinPux5Q33i20QnNu5fQUJJU+ntvUWYMU+w3w+wYJ+fBmLJsIdqslWoA7Vuekm19xJlh/hUIMKNnuuRtCKcjb2pHPcaZ+eR/HI9mOHjwjxHU2fvVUNGtx7D/KBKxfStLBj5cgx0AM6DMBY8UFfku+z0ak/bR1fTDybJZcNra6ulzOmxhgL1mJ4atbQEyVy37h6Mpyx6FNA5le2ImDMC1dktYD2Dano5cYm7QC8qnwmPsEz3AOShQ8L0kGU8JG5LR++f/Ub6GA2sLBAE7wLNDz5aiHnmDvBzoOG1AwgrJlsHQJKvJoH+77jCUFbQqPdwLCOXYMtX11V/C1e2MwHKqb++uBxudg882omkm2HbC0hGqisy49pMzJy2YIIhAOLOz/OJ3u4mpm9UGv5kfB3UhV3s3bf0G7nsQWtfdFBwAMLx+pS5FZpBxIuxqIElBuFqFMhLPul6nmeuMbdkQxdVNlCj0mzOf4SKvZJRsBNQVAd4EghcCBXp1CMEfSsOCUqeCCe9dyrPeTrhId5Nsj03Ft3bmqdjOJyHNZEpGFHL6xd6hOGjx034NmGVqj5gxpgSG9iicff+yq/nA+Zuw=,iv:9WgCIMnxWsQRP9XPoDG3+0joMw7f0QSpBpHnwxWOYPE=,tag:GIkd+EVAxAUgmI2Txduy5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWTA4a0NWMnZueEU5VE5M
            dEdsR1drV2RYQWlVWE9qU0xMRUMzV3lEaG40CkZnQUExSkVpOU1hVlIyUW5VMDRO
            K0hpQnN1VkpkajZlMmhjU3ZwYktRWDgKLS0tIGFBa0FrMU15N1NKQkpRVlJKUHY3
            WU11bllTR1Nudkx5UTJlODBwS1krRkUKOYC26vnIllLO8ndx9jV8SvhnEa1C37Ec
            XxNfd33EN48ARKe/B3qz1df+6fF9EW/Lu5tpr5XZ8D5MEze7+oeMTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-09T00:25:12Z"
    mac: ENC[AES256_GCM,data:h+s0wx8BD/ZsJbZQehFcZauIXGN3/V9UjOMhh6Qg94z21jbamkswlrz6wesstPtQsOC94xXpKF3Ae1ibXyAidkfyZB0qJPF6iBeOOyD5vmXRK7SuCFPpz/DSWiIxwO7N2k1D3NjiJg9SsoKd17KNFUZMfT8KsZZ1PGWjgJj+m6g=,iv:d+MbASTlZLvg0tLPW+pbsyJVL8KlQ5vLzt+khrNApyY=,tag:5NJgJc69Fp3+RGFTLyQz4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
