# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: kube-system
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:HOSDS+9Gvz3Z/bGhhmAsm62x8lWqPwfM6R+rNRmqWiH83zZ8rJl4VzRi2OVQxEXYQbN8BXNaGkeomIuQ8mr27z5m5SBqYnfbZFqJPvD4+UlIFwPw2FnU1v2F4L747in3mDkRFaWH7BwDCW0D/d6fr1cpcFB+QG2VyFy3LT0KDLm4JhbW72fgCt7AJJJ95hWpviA14tnIq4USNwX/c29/iP4VxTerkt4dE9x4Q/DWiVperYvKXzjdlwdwqq9ucym4v7Srh5q5YkItDmwUY17hcmSkQKT/ol7xGKsjGG9dqZHj68a6cXhLN6P62mf+F5phsttIJesrhs4vGiYS1NSasnTuHDmo3/0RrwFuMVzWaJNQhqdiLsWihhJM/U2L21CZKNXAXQAALXkPaTsbaQEaDahgCOCSpXPi7U2MbGVE4sg+vHaFm5SHZmrFn6ZmVrdXO1Fc/9fvHvZ0Ko7Vws6l1BqOiZPOCqPPk9pCQRCPQJ+bIJNdLuWGC3UzpV3kZLmXCsLwnGPjsBXvVGaTinWMVigeABSAHGZfpFthKA8bd/7kWCNi/ubXptN67AaBjz8Vuw/7DH01r2Qy+L45JE9PQOOq9+A/tfTnUzzCdG4BxQ9/pRXhUmh4XZro0/5feGtPt5oTQcJbr7AKNlL6FW5Pak8/DfR8wFVOUlB6QmKPkjXBpHGpVY6OpC3uMzXsVqbFWIrCWLZ+KGJvWGEATMthXsUKtMzpS5DxmJe95khH59Cm66iRm9KxsKm2jyt2PeD0Eno6HmPGleKw/0z0Rrjva7HNXp18OgjA0Rvr9JnrXFM+e8SruQkh1xbLMVcZT9k1gcTw/kLN2LhnjrxbFDr7JhKwfKLzKkwGuzAyHhw/lBMahS3l1dn3mtpU05GDcyNNMDYIO3xipREGArk1tqbtgOs/uBgHcE+S7gtIr5PyJATK30NiLcfI7dVUFDgT4j1yisrO1PPdnw5qjNmIkIW6mLnUGcc5oAND0lHdyUHhbboBa0LHmGdCn3B+pFZMjuBAhX+8MN3zVDCWdyGtMoSRR8ok8KLFlsGNMPS0kskSGkx3SVODwXAs8N9wEncZquBdJA7A0G6JEWMtOCyc06wKYCsX/DbCMa5TTObwXO7ROLSLoUy44+rYYIDf+0NGgNvdhxzE03KdkJ6ezoIh1nVgpIVSQLFnxmsJ28e84AEk6+c+SaUn0PS1hWDeGPkENNQlzDdJNM7dtXGIrMtawqS5ofy4FJwUsvQ/uLVQUYUnXi55NaAwIsCTKuf9BJnN2Z98WlDpB+HIpW+Bo2apoCgSt14sOVIvYakmRZwj3+Q9MdHQhVoSmOSLg2FbcVz9WfDTr215M5qSUJ6jab3bMPH/sNN6I/7Qvytr3R8uSABBOArLcop+T21tmJQiDieisT39fOeWQJbAIySOEME37Cbv2Oa6Pg3Vxjq0aQ/nggtdZ+eGT04HQ4apll5SGAd/ikNSozTdYoA65rmcggwJwKtkN4n2cq6OEdrEHAalH1tjSQ/NnfqzgmajLL6ZHQy0k4IF1fJ9mY6xo4c+xyQw6KlRlqHl+MeBCM7xYe2gXkEKosBQnwmxxmNRc+9AGYnGPNqKjTAfb+gLeIyfb86nF1G1s4+XRREvu8GM5KqvrXbrvGiyiRQCIshD5olFygE/pN+r7q8F49dgBj0rurGb2t+wAYbySdyVsFcGQcm4DVM2m3FxfSDHIibz4QbWvG7ccll1Wup0XgpCEtyfWP2raLi9x6TBSr1CusM3LEI08GPI9IQYNNljTUo+yliMnPaG2Dr4XTd3k3jqDgbIPe6/nhisAORucn/0QTNB3HGweNfVij15UVdAkdAD9EleQvihCJdu35Z8oTxlxbZpyT3ynnYf4hzV9cTOlEq1A4WquljLgW3+AQXDFZiFwyHh474/vORFLB0kgKtW9RYZV4I=,iv:U5huPb9YL9TN9eHlz4B0vGJAIZ3cUNWYoJqFFwJYcag=,tag:Hu+oqqYtdvxAg8u1zAf6tg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdisreUg2YlU4Uml1blg1
            aHBYRnZuZVY5TDNBdkNvdCs4Kys3Y0JwK3c0Ck1KYjg1UHFWdzBOVDJzdlJKYlk5
            SS81bmJuNVZidUY3cVpHSnFudzBoK0kKLS0tIGlYNzJxN2NaMmxua2N3Y2pucTNF
            TzRHRGxPVnIrNHo1d29rWWFXRkpQekEKAm5mflXt8mc2Ukqnu5ygu5zJESDnmmCF
            ivmv5UwA9szfPL6i+2C/zB8ymqbftwjbdv3u1L7RDNA5SKgIYJ8p7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-10T01:50:27Z"
    mac: ENC[AES256_GCM,data:ZhKe+GmJDqBlBGEBqtVybwZRd9DPWHIOo80ZtT0O9UtCeDvH3zvorDZu6jjMRiAeKweNV00dAhUGZAR7OGLFyLykWRY0hSj4Xr/6zqr8f/g2b1BRk8yCDLGyLqLd2XF7cqLcVFGVw2JBu0xaaAUaDtvx4FW+hrmYUobLEKr+rFo=,iv:zmZne8ocYrVLOLvELYCSAp/1cs3pekOzONt549ZSi7k=,tag:rFB933zIOyXbeUXVM5zLrQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
---
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: kube-system
stringData:
    token: ENC[AES256_GCM,data:Pzqt12DvI6j5nC+bm2Bdf/d8/Yvw2lOLt+9ZDfTOUAOKSfkKz1lyDINO865YDYC6avEPp6jbkNFezbY0unjLJ8tp0VcrSsxGlH5XaQaYhIF9wxUSmnKH9PzcohUrRHqAp4NpiCWp17oQCXE9yJW2kFfQzGZVp/FBCg12PR68lQZzcnU0Ad7W0nps3IGkkVD0WqhTxNxpdwx822HQKwV2MDvSiUUlIakOtVmzTdH8QxTa9HJKDZUFhMtg0Tlc02ebi3+nJHMIeJm7J/zCM5i3pQ/vbZZCci5d0LDSED8yu6RQVlbiTI4IYa25k9AMfC8I7xl2BNtDUTjbUwO0zPBeYIYiZ660jUq0CVIKdn1O4ig7QQNgl0Mhb16j0flp6k9UrBfnRDWWSDO6MdfM0qT85JPVu0aKGPVu27vUdAiZJb8nXiD/fvOkciBnk7osZTX9W0gN5ZsC9EbzouYygJwzDGGfpouHNiJSFlgviCDia12/mvmZKUHWaQRCja7UBF5mmLmblItuoQQuAWAWY0ZtEXj/It8rAZ3hN33fDkSy9UCw1KlZ9BqpXkOKk+Vm9nT4Lshyzyb/6Htfy889nUQqQMELi9Z4Dw8VNiBFqihMG6BVHyIXvVdOaOAhZa8Twx31T5BJZRrvYKWdRBL5kqoq/qj2m6ZN1QAkvpKT7HYC7m1djxpFGguahZ94D5iTEu2SP855roEw4TWlwrJNNWczQZXiyvzqDdfc92aN40WIZZN95hMRRKGJi9nKRgkEyVtPGPBP4iypHlQIxT6Do0oiOOqhe1z6qj9MJng7zR58Mie2QagvPsc0WAv7FIAW1rSN9KRmqjDzX93jWskAxjrqyAzlqbnHjqEpwmzZ3pe+CKhV1CB5r4iYJXYuXTiimPzPnlfzDGXVwY/+NmBGtk+6Gw9/xrv49Pg4NCQ=,iv:XkNSY6tYC9vAYJegLsmCWl6NQZbBINxN56y7hCzxILk=,tag:F1mCrJ/TyvlmYwdMAn4oLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdisreUg2YlU4Uml1blg1
            aHBYRnZuZVY5TDNBdkNvdCs4Kys3Y0JwK3c0Ck1KYjg1UHFWdzBOVDJzdlJKYlk5
            SS81bmJuNVZidUY3cVpHSnFudzBoK0kKLS0tIGlYNzJxN2NaMmxua2N3Y2pucTNF
            TzRHRGxPVnIrNHo1d29rWWFXRkpQekEKAm5mflXt8mc2Ukqnu5ygu5zJESDnmmCF
            ivmv5UwA9szfPL6i+2C/zB8ymqbftwjbdv3u1L7RDNA5SKgIYJ8p7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-10T01:50:27Z"
    mac: ENC[AES256_GCM,data:ZhKe+GmJDqBlBGEBqtVybwZRd9DPWHIOo80ZtT0O9UtCeDvH3zvorDZu6jjMRiAeKweNV00dAhUGZAR7OGLFyLykWRY0hSj4Xr/6zqr8f/g2b1BRk8yCDLGyLqLd2XF7cqLcVFGVw2JBu0xaaAUaDtvx4FW+hrmYUobLEKr+rFo=,iv:zmZne8ocYrVLOLvELYCSAp/1cs3pekOzONt549ZSi7k=,tag:rFB933zIOyXbeUXVM5zLrQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
