ansible_become_pass: ENC[AES256_GCM,data:G3BXEUhKe1Y=,iv:4NxcxT6PsOvJuXKxCE9NtDRZ81dJJlX6KP65QndiCM0=,tag:vr212Japlz3n3mFSa+cOjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbEM3Y00xWnF3RWpqbHpO
            RnQ1cnRKNEtvWHlKRVRIMjBEdkNLb0pPUmxZCm9rNE1LeHhBNDVMSVRkME9hWGEr
            VXI1dEtKMzZNQ2ZFSjA1RmZnMlZlK1UKLS0tIExTVCtxaW41bWw1WWcrdWdGaFgx
            aVphOHVHWmt1NUhvRWdWTERCUVpNTDgK26R3OXhAtOudy81SbKOz4PwqRzk47NrQ
            1XOEC/52IaAdI+IsMgnBX/GRVKreJ5kDs+x5WjEDzgZ2Vhcyts9ULQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-10T01:13:05Z"
    mac: ENC[AES256_GCM,data:8vAIB/mVQQ255r6XIKpAnHl1Kv3wXD2VaZtLTcdJulOovt4qyQIlRtcmU+5BJzijDzwH/6+vt3W/B44A57iYi5JWYrfd5M0qTZ6aSKJWOxB1yAiVKlddSoNey8Ycj/lKxgyP6HwCS6vtoG1HtGK8HKtEwLYUU7B53BGMbJUYS9s=,iv:vc+60e220+iFcuI4zDXBiOn3WUyxPtMVhiCGAnbwsec=,tag:M8Rx3H4nJhPMnGtEjL1kkw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
