ansible_become_pass: ENC[AES256_GCM,data:+9UpOZ7mRac=,iv:WGx2ztOXkftkzcmQ4oF+IzjBrPl5CgiFYWO5SIGS8I0=,tag:TUEBmyysTpVnVK3iypURlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByREtvNzlTaTcxaGl1SUdV
            ZzBIZUs1cVlKMFQzNlVNMXpkdXRjRWtEclRvCkczZkhoVXUyWHk0OEhKRUVTWHk3
            K290MUJxQmZhdW1mdnIyMldLN29xUHcKLS0tIG5qTGJ3VzZWVXgyUlgwaFdSdW11
            eFBzZlp1WEcrNlZwWklxY004K3kvU1UKObs3S24CyhM9MCw2Tb33r1FqENnrvbmv
            5Xk0r/AHYHbbUF6Lnr7ee/86JSPC3J9OQWFNAQnGqXz98kFT7kq+Wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-09T00:41:08Z"
    mac: ENC[AES256_GCM,data:Y1QDVFyzFUwObbJC8aiLLgAEtuTaXWy0bsHltU1gs1r58Wr1yJlUBKHhib6ugn68i85PSXwpGAGdJW6ir39++2umJGIztsj1r2tbwuFaZKoCC9Z1twZP/qUkzhfJGCnJ5IOXMUsZ7PnJ/psnb0rAS2q2AGf7sEe+efH8jBkcdDk=,iv:6BLUq1Za+vswKvoLMYBava5qxcvc3Wis1+erf8h1/MY=,tag:m7N1McM1QaU/BJEWU7oB2g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
