ansible_become_pass: ENC[AES256_GCM,data:toL/DnEaSgU=,iv:V0hpIpHfGahRYCsVyIDm05e8Yc908TTJ/ezR99keHho=,tag:AthXzz8qBz5q0CPl250U9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVVpReTVMUVZoa2YrK3Nl
            cE1NVlRRYjdmZ0Z6YVNSb29iYVRxV0NQRUZFCng1dXdFaDBtSkhGRU84eS9WZk5i
            VVZ2cWJTZ1FBRlMxNmVaMnA2dlhQRGcKLS0tIGg4dXNVS2tXQjR1dWltU3RlOC9o
            VFphR2FPSW9UQjlibWxBbDdZcmpNK00KRtGEhvXSWc698B9Mg86ic8sRm+genGPQ
            xuUl03FRVljWA7pZ5J0XX+htaD9BU3zSOfI5pGONVlFf87+1Kh6vCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-09T00:41:09Z"
    mac: ENC[AES256_GCM,data:I7hOiDWkwF++wSNI5uIJBY9FhmeG+mpxbN4dLTxMQeW79BhdJDc00dCAEOMTnkXOdKQ2i8ey7qgTw/gae5k04UQCHqQw2Ba59gOYq//NvJrIuwUoXNv8WQISt/ncon5QVRUEXGY7EjnEQKRDlR8YaPX+7W2ftotV8/f1Pvw8BYM=,iv:ba9B7hupFmk/ViTsw7Xr37AxUtUm/rVaNH9nat3zmM4=,tag:+gRUzE3GqqF7LXmVIpx0KQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
