apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:keK/ylpaPhM=,iv:exvCv7F27bpmAwptpSnXGZuRPk6I2d1wBPUvCRcU9q0=,tag:PNURvNFZipw6LDaqo8tGjA==,type:str]
    admin-user: ENC[AES256_GCM,data:iQQFCsg=,iv:gXqev86tppH9P0ANYMIYeuwVROrWnOsEMDPNXew0FgQ=,tag:JwFK7u+dFyMeFFfl6MKuqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWng3NTI5NFBrbStoSTJJ
            NnVEcUNyQndnQ0o5RTEwRVFHQ2ZvYjBvd1JRCktEZ2ZNRzVvcWdUdldranpHRmty
            T0NPUC9QNXFQNzlzdHNpYXBPK2cySDAKLS0tIDFBaEpSblFsTHAxWXRJRkFuMGVL
            VFlKemsvNVgxZklUUHMyR2s4Wk13WXcK5yAgPSpHmykzq6KNnJscW2GePpeToBfv
            pd01FMilGpQdOzPoJzXsrz3yGKEYgD3iJFTJbOsGCrNcQAO+mXRnFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-08T23:50:54Z"
    mac: ENC[AES256_GCM,data:P2zlncSaYxU6RH1hJXj+SEpiipbEEvkEiEBDhGVOYXfmOrq02WUzv3R+NQDPnN4NxHBQ6vPp1uSBZ1Jm9Jjqs2Yw9Sr5+pZ68sboMYiEWAsC0M1RoCRjybiAS1yYe5PT7Hybz37oRE9vDOKcI6j1nYrAMREq8RMxNu74DUV2Osc=,iv:5VqCz80jLK63nyLTa2xwXIDV/tKHPhJHKZe5pT9rxUk=,tag:nPpWJBtSmgkT+eXJ3Cq+Ig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
