apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:OUNuHmn5t6efT2d7vYu0EpTaDSUM8TyH,iv:hFY3OMF7+3+JbHzmq2TTNBym9Ju5Ha3DNMJHveOglJM=,tag:liBeRgaMjBvJ+8V/4j4TcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJa09DZ05IMUFuR1FlWXh0
            eVUrb1JvSHQ1dC9qU3l0RE5icHdWVUNSMkYwCkluMFl6dWlRT1VUU09kL1YyQlVG
            SC9VcmhITjY3a2pYTXd2Z010UWJzdDgKLS0tIDRWZFVVWlVQQU00Vlh2VTFsRHg4
            ZXYyMWhTZ0VOZGs5bFptZ3RSUWc1WmMKcUiY0qPF1XZ3znEbGlkj29RPN2DfWxOY
            U67XG6gwWMzwRNkqeQahZ4WFbUZHAZAAtb/7Ha4JDBdmKjN5jDkfoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-09T01:21:03Z"
    mac: ENC[AES256_GCM,data:aZbhjUi11G2btkP0DDN3DVljAK8ZMPpvl91Xl2gpA6g1eV5rvgUKXEoXL0DmKBazBn5EC0n0/4RzCHiBbJ1wCnfUs8Mvjzdvz4jpGospH0vNCFzOnvjlyzqgbAVgEcM+Rn+hm5WS+n14VKA1AqHIgTS1ePH+TMvb4CPUgWkiieQ=,iv:EWpefX8WxGMSt8bNgfPrjaR+LsGjoxyHV9VMf4mgC4k=,tag:nLiKqn6LpjVd4ZhxaBgIPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
