apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ESEHpc0tNUnKGxiBa3eOPatfpAlnPfK3,iv:VBO3JMqPf3sqHdjziP6o3ASVo/R/Cd9LIIptD2utXAQ=,tag:UEQ0OQECcCasHhRS/9xJww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WmRnUnQ0a1Z2eEI1RzFx
            MXAyUEJ3MGNRSlllRGthbHRtdHBEL2xpLzB3CjJLYUJnb1NMeEJzell6VDlMTzBv
            TUwrSi9zYVZIWXFTL0tCVHlJWXY4Rk0KLS0tIDAxVjRLLzFJcWt4Tm5XNENNNDBm
            UGtXYUMzc0xGVG1jeDdaSHlzYjh0cXcKhv/r0MG9AmNkl6XS+6T+nrF+2A5SL6aa
            bTa/ENnLOzEztZ2yzGd6RkWaTywc4bmbXhrXLHMalWaFQeWslW53LQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-10T01:14:26Z"
    mac: ENC[AES256_GCM,data:T74X7WXvHR5C7OMG80AHC3OtsSciRIxzYMlB/58allaFiNAELoPJpctpyv+wTNI8Ho6GNAWbUhgPmyze20FZ/5o5rDPHiPWF76aBZYQBtJ33qT/6vx8t3NsIvzryS/c49SehG+SEdW6r/wD4MNU/DDU7nRVLtMlCcH6l+EbNM8A=,iv:DwCXo6uX/y7fNaIJCXZ6eYXg5UG+5KMcWFDDkTcFXt8=,tag:SmDAtZCdGHhzTMzaBSIcCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
