apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Xvl+8PmZWJKAPzk7Nf1gHDYvlHmfWbWR,iv:s6Qt14+HxqmYdkTCaDDKyn1bU/9V0FTq+cerN8V5dRY=,tag:XC/VKWr1jraOv9WiMtj0/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVC9XQ2s1dmY1YktReERO
            b1hodTB1UVFkaUx6SEt4SmdSamxaNXBRdHpJCjVSTFZTN0hqZFZZOGpvTklrYm85
            SXhaZWJRa2FTU3U0Qmp3SjRrWmJ5TTAKLS0tIEtEWWlIMG9PZi81bGZlRVluS253
            dzRUMlIrd200ajdWNjdYckZteXM2RlkK6o+jRrlRk1pgK2O78DCQ7W5XbDLCzuaZ
            HcStDodLQWNnSMi/3bljWr9It7H+EcJ6/vKD9R0FjO75ZZxoq3abmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-09T02:32:09Z"
    mac: ENC[AES256_GCM,data:E1lEXUvYImwLlRvQaGwceCUWBaRC1SEMDpGz6NpoCtAQuxrVxZcL7CKwIC15W2Z76XpTWhoxN7UJn5keeFYU8NKXW/C92cNdgAhI3Wov5YDmwlQnO8nyF76Ojue2K/xxZ5q933CLRNTRWBQjnyiBi1V/PYR+RvofWaxv0JDNjes=,iv:bGiVi2U4XgK3+LFAP4vqqIyMPg1ZwFTtCb5oYVYJ9bk=,tag:+/4A9UzlOPNufN8dcGGPTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
