---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        type: deployment
        replicas: 3
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
        initContainers:
          01-init-db:
            image:
              repository: gchr.io/bh2754/postgres-initdb
              tag: 14.9@sha256:b2db501df80256f421126ad9bdc1bb128147590aef9718c43cf5c3bc4c8a2194
              imagePullPolicy: IfNotPresent
              envFrom: &envFrom
                - secretRef:
                    name: authelia-secret
        containers:
          main:
            image:
              repository: ghcr.io/authelia/authelia
              tag: 4.37.5
            envFrom:
              - secretRef:
                  name: authelia-secret
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 250Mi

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        ingressClassName: "external"
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"

        hosts:
          - host: &host "auth.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: configMap
        name: authelia
        subPath: configuration.yml
        mountPath: /config/configuration.yml
        readOnly: false

