---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: abs-config-v1
  namespace: media
  labels:
  # snapshot.home.arpa/enabled: "true"
    app.kubernetes.io/name: audiobookshelf
    app.kubernetes.io/instance: audiobookshelf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: abs-metadata-v1
  namespace: media
  labels:
  # snapshot.home.arpa/enabled: "true"
    app.kubernetes.io/name: audiobookshelf
    app.kubernetes.io/instance: audiobookshelf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block
