apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:oEH0ILENfY1/bYKqCrteEV3yby7COQDAi6CIKGeF5lAe+E4YBKUcSA==,iv:4TLA+5zeyrff7iuyI0mMvmJXIx8zCtyxx5++5evOG2Y=,tag:LJRM0xccHvddo3AUsqNUvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cStWK3FQNHJLenozaUV4
            MlU0Q0hOY3RGN1ZLYXpBMldHYkRGU3JLMlgwCnpqd0trZ3JXMnJqcUlrVndIOWJZ
            MW0xQlI1QVhXNkxSMGI2SjR6V1ArUW8KLS0tIEVEaHhsdHRiOW8zVG01dnlURElH
            L1d3MWtOZ08wdi9XL1c1ZitVaENyWDAK5vFmJbnvfwoAFo0Uhk0GN7kqDHEjTPKu
            XIxUo37bQqgPOO/TDdYpz8/6MhkLRiTyog1O/jawSwKQ7w6nri2qkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-10T01:14:27Z"
    mac: ENC[AES256_GCM,data:6vlNwj5rAtSm1/a/6h3QThzJgtfpNpUi+uePfoE/BPElAAhDmqI957vkt6zgvTBcmcdSfkkSacz35JvRUlRZPOuyOOZpgc6gjCxD01KSq9rTPGUk3IhZi+MvL2ht1buTp+Y9mxKLgp7caR5WtqaK4Dt8L1zH1wAGAokIKt5pnKY=,iv:ScKNxt/Q1paPyu9VDEdnfZtqEBJmINkjuj4AGqGLw9c=,tag:IBm4WmQvtbbsBbP9dvvdkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
