apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:kG5hn7BIEqxJzlN94123ZGukNUvDf33M/KgDoOWKHfOPlP4jBc0Qew==,iv:b4ib6N2BIMfF9VysSEULYsph7gkTs4dpvLKciH9x1Cw=,tag:Dl6M3cXWeZeX6bcD4RlRNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcStmWDJ0VFFOV0krdXBR
            bHBBc0Vta3ltZzF4SWhTSjZpaGk4SUhTNldJClhZTHR4Q3BYTEZqYjl5N3JHSElK
            ZEhBZmtlYlhzNVlGNDlHUGhJbUh5TmMKLS0tIE54QnBPL25QdyswTmVNS0phaWFq
            aEZXb0FKUXlpdmVGcU5BZkxTOTVLR0UKNx2sf9MZlMMiHPSFXohAXwN6wTzBC7Kb
            AaOpvHJlPBaRA5pFeWrdTiqX0qjbx6haoD5FamxKMnLqVMYBTjaKpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-09T02:32:09Z"
    mac: ENC[AES256_GCM,data:ZqDEeJz04XMr69VNmCt17gJbhekTQULrBRJEPpiEaSRfZLCLcAe2ceR7d7j+6UOFHy/smwoS8dDl+LFL0gHnQSWLMe8+h3S47o4JyY/Fj7jlDOiYe/jfYuFH3s9zPbhFt10HoumQ7ZVOT+6y2mvvNYobCMs1j1xi3YFhzYa5JdE=,iv:0K7x81z4Mg+F1gsuPcTbcs2W0nQwVEliFJ3TyxNd5+M=,tag:yQaFb2ZC4IGkI8NWpqjMaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
