apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:Zm9Eqkg+GM3ytgKqy1ewPpwGVKqHB6vdp03SDAeYbvWWahQS3eL+xQ==,iv:QSfaiEPme1NqvJmYFIuudr+A1lIoA+jzB6saHXtIlK0=,tag:3FH+bBU/Gd0XO2YtCr0a6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NFpkMjFuUVlyTmQxRmRu
            V0U1YXM3NUJSTWVXSnBYQjRTVEdvWUtreUhFCkUzREx2VjZnRmJsTGxoU2lVdHlJ
            VW92UTNDVHBBc2E1Y0wwaEpaWHBTdGsKLS0tIEllcGZDaWZvWS90MS9qOGdTOWpD
            RWNhaGErMEhzWUhqaklqOHl6QVFUbFkKcJ4NBY/3SgE5NWkNhT1NrPw982Y3dJVL
            PXaZ7LBOj5MVmyNg5/3pAXB/Eyhqs2nF1rtzjJFqTXWQuSf+V6py/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-09T02:10:51Z"
    mac: ENC[AES256_GCM,data:1p+j2TaXO7i+MNZ6QBfcdTRIWaOcaPd8bIcJMcXLlKMD8nlyl5LgUa5eWXAPhzNklINs7yxDsPpLAnwhe4sJE0dCO10wH5d9ydqGsgeCbxcK3IkE2MBuBJlsLe91kKGFjXjlILNtqBFEpeZ9dvSIKuXPUqB5RziVfr/7kT5IOjw=,iv:TzD0DBBX3nLF5TzuuVBExsIQU5vsW0DqsIV7VjarMiY=,tag:wTXhkZ16IKhquth2I7Wyow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
