---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nord
  namespace: vpn
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nord-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: nord
