apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:7iKQuajS9lGPC15OJ0utf5Jktjwa/moiJ5ZuVEO+SaJ+uK+qAHa9Rj87WjwogwmNvNUjBUQ6oicSuodO,iv:IDz9AReexbUb14rL+BIrKUOAzOiN1+TJGo1TVPnadq4=,tag:OPsJF4kPvpIV1yQ5joYhjw==,type:str]
    username: ENC[AES256_GCM,data:F+IAJzY=,iv:2eyDJ7UiabxYCfm4ZtU79rf6CLVzccFLAK/TQ1k97m0=,tag:+2nRit2gaNCM3+57WTDpdw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WWYwZDRRdnFtdDZhSkFM
            cUJOdGpYUVFiVkJtTmxYTStZYmVWVHdTZHl3Ck5sUlZlZ3R1TVFQUU9Ib3JReWNP
            ZE1VYnR3RmpNbFlmNFZ5YW1tYjNiWmMKLS0tIGNvb3k2eWZ2WU9IbzhQMXFSb1pZ
            My9MN2g5NmZQUUNaUkI1MWd1WllmOG8KzYZh8vEmy2AnYcBkIupKcmbP7XGsoGWu
            ZkGqXw5V1GCX2V2o8GaimyBW0bo9F7lqvBw1uC7z1p9Uc4hvd0IpQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-09T01:21:25Z"
    mac: ENC[AES256_GCM,data:b+Waup2p0iP6uKVjT/HfKuM4Y1nW6xgpR+nFVduzhSl6VR+vMe8IBUUMzPaNVTj1svy303c5xkeZ0gXwdv06L4qTQBcq68r0ugPb57yVPdnWWSbhBSw77EaimMOtsGQB0zkQ9+Rgyiref+Cg9Fz35uO/kRN0Zd3RuhI8ymIuaBo=,iv:hFbQ48go3c1qAlgJtteQFEHCIfWg4ggbg7I9d1WbGAg=,tag:NuZawxj8PbG/etdgxH2dRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
