apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:qRjQMkZeY6qhxSe5NakV4CPxuE704J86cpyj1AUJkBwkYZz+0Y6EHMb9r0oAZ0I2gPn6rBQW6fzYAaBw,iv:3YF286abkVIWplCj7HJw31CeMB9wyeERrRSx/O8sSck=,tag:9Z85RgzLJWi0ZdRPpUjtmg==,type:str]
    username: ENC[AES256_GCM,data:TPAc1jU=,iv:MnDPsD3uGg364XL6ytHNehRSoqFuXFyVX9AUOs3uqh0=,tag:Oudp9WCmT/eGy18VWExIDw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNjZTS3JEcmxiWHZtekEw
            bkpJUW9HcDU0ZGFud2UzOHpzVXdwU1ZZbDM4ClJoOXlrT1Bsb1dlVVZlN0k1dDFz
            cExaL0FPaVJsZ2dTVU9nQ0lRaktnUlkKLS0tIERtelBZc3Ryck1aMGR5eFFVNEU3
            dmNXb1E0S2ZWNjNPbkZnVmlDMjM3d2sKiq1tX+As2NUM6a3hiPzCfq6TLfVaTr81
            xLxl0LLRfZO8hr8axcEW7FqwZ/bBzZRoHjjb5o3Ath3ufjUxJblt6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-10T01:14:48Z"
    mac: ENC[AES256_GCM,data:t+4Dlj0IGdoUb9GHPnsLDs3XxljWxmKkW+M/A46fgh0xlMLc10GjSEZAF8MXDMZuCXGsmpsjaxCJ8Q6NvfZgN4BblMtCZetDAw6ivm2hI2odilFwP6Xa1L3mjIhdUHTjHXO3XK6DKI/mmPRwVMxKix/o9AgnKzEWNPKbz5GmXc8=,iv:v5NW3wZ9818j8ovDKVITDtWL6zxOtLpjSXb7U5lv+50=,tag:Z55zDvxED/UfTPNTqVwX+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
