apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:6rPgAc16GByf54O9,iv:BRhHYBbZUITzy8C9ku6Tw0DEMu8ggs3ZNHY9orGU8AY=,tag:CDkEIShxM/eE2+cn2mwz4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNmM5WTZnSjlyUyt2L0R5
            eVhwT3g0eUV4R0pkUDNSS2ZIRWFqZDBLWVhNCkRMS0g1Y0hXM3o0YzhZeTJGV0ZR
            N01sOVUwbm52ZWxBMXZjSHBzL291MXMKLS0tIFJVa1g0WUt0MXNLY1FwUzR2ZWlI
            Qk1RZmNTLy9NbmFNbUNDWWI1Z3IvZ0UKm1bmNamX153KT9GvH6AJqTucDGlpC3sQ
            Tt7aGJCiERc3/CBpqKSB77BX4+IVBZL0bI1AP8qhWUubkl1hFEAtmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-09T02:10:52Z"
    mac: ENC[AES256_GCM,data:IviNBcxaKlEFEwQTCN/RyDcblkZIiAEZJYZEL+dFpOZSGK9+tSzgr9OllzyPxW1bgknFxXcR62lMlCBLbEexExUjJFVUxNHnqay4e+Ygqxb9GXdJ9C7ME1SneCopyL/Jafn9M1aK1tInMk2VBVZ2CuHemr+9rTe1DPpbmBegpWk=,iv:5UG8/PcKWEGU4DfkTRebAb5LZ56LHcikUxwXDBGEXQw=,tag:zS7zeqkOK2r7QGprR34JCg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
