---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app stash
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      # -- image repository
      repository: stashapp/stash
      # -- image tag
      tag: latest@sha256:fce929b57f1e382731eb57b54b21725600b0f787a9300e022d8e5e8e4641eb72
      # -- image pull policy
      pullPolicy: IfNotPresent

    # -- environment variables. See more environment variables in the [stashapp documentation](https://raw.githubusercontent.com/stashapp/stash/master/docker/production/docker-compose.yml)
    # @default -- See below
    env:
      # -- Set the container port
      STASH_PORT: 9999
      STASH_STASH: /media/
      STASH_GENERATED: /generated/
      STASH_METADATA: /metadata/
      STASH_CACHE: /cache/

    # -- Configures service settings for the chart.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            port: 9999

    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: true
        ingressClassName: "internal"
        annotations:
#         cert-manager.io/cluster-issuer: "letsencrypt-production"
#         auth.home.arpa/enabled: "true"
#         external-dns.home.arpa/enabled: "true"
#         external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "television-box"
        hosts:
          - host: &host "stash.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
#           secretName: "stash-tls"

    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      config:
        enabled: true
        mountPath: /root/.stash
        existingClaim: stash-config-v1

      media:
        enabled: true
        mountPath: /media
        type: nfs
        server: "${NFS_SERVER}"
        path: "${NFS_MEDIA}/shauna"
      generated:
        enabled: true
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        size: 10Gi
        mountPath: /generated
        existingClaim: stash-generated-v1
      metadata:
        enabled: true
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        size: 10Gi
        mountPath: /metadata
        existingClaim: stash-metadata-v1
      cache:
        enabled: true
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        size: 10Gi
        mountPath: /cache
        existingClaim: stash-cache-v1
