---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./config-pvc.yaml
  - ./helmrelease.yaml
  - ./volsync.yaml
commonLabels:
  app.kubernetes.io/name: stash
  app.kubernetes.io/instance: stash
