apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:XDwc+W3UkwpTeuUgsvwJtPAndYNB6cpA07Jh9K2sGhvpprZY,iv:iUzHdEil24PnrhhAB0sZpxvb3fj7SvLudR9u945P0bs=,tag:GNqzWrX+VxqRXmljxsl3nQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:ZsJSwKd9mm2DypD3Hr4Og0F7CoEctwqW3Jun7eFigHHIo58iQSf6rERccVMje0Gn5Zf5hA/TJXsP+s/BNaTXa+SWAi5WM+3aJVPGNmLKi23McFV+xR3F0iFA9DJFpdr70Osie4ucW3BCDGqZ47FHd3vd/rWNsmLQDstHMB0p6J+7U7Dw8xPb6Ms/4SAtDlfmb3pIyLmRjwG8vlCkRSrjVo+/2JGzWpx2QXgLzkLdDtD2dW0=,iv:2BmVQLSRA8bUQaggmDXsjdJiRw/ha6h+3/enc73GvJc=,tag:tRTxWPx5nEneJnIQsA+O6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVzBEUHdERkQ1QUh6UExD
            dUl0bHBkVVo2MERSQ3psd1RrTzJTa21DVngwCitRbHB1ZzZwV1dHc2t5TkIzemVs
            MWIxNVY0ekxjQ08vTmRTeVV2UzRzZlkKLS0tIGNVV241cDVDWWxLQVhuSHVwaGRO
            WlNHVnF2RXlxQmpkZ0RuSmVCeGhTM0kKolzfJrtq+FXoSHdXkeGqccvt5c1cPiuj
            IbDMz553vbqTjcul/D/gD0OUMPHGZRXs+lv8hw+PNNmvQy6NneRqqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-09T01:21:03Z"
    mac: ENC[AES256_GCM,data:SqEOblV9mFoMBiY6yB8sUaAmshOS+Y4KOZapmOIPwIK+KYtCqn7B247iO30UGDB2hPsix1JbIhY66fxd0iBOUTcXKxhp1PH3kkFGH+Sr6xHcdQbiFXbzFgSQ+KOyKXqhkD/YgjEDv7oKYVpcnI5xURovs09vmY2SOUPYy4TxOAQ=,iv:pPGEjapviO0vb/aEJUp/n16Zt39VbEQk49qrJwDNxMs=,tag:4e3rVf0itCY1OrSjBGmgGQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
