apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:361X3fEYNJeZ+5kvEqPDkQSwQdVjZAAvn8tb20WAK215q16i,iv:cslMKqvhRqQu0QIkrHvUYGlXg1c3uT4YblpGOUFmUHw=,tag:g4WowIIfqT+4agHLhhqjkg==,type:str]
    credentials.json: ENC[AES256_GCM,data:1jalztJ0pDNCCnqfVVv9WyUls0CefoBYwQGa03q6bLs6gWpXJGybG712Jtxd+/2p0IuP9mj73Ek8yDDd7ws7iGkak7X8ysjgpl0mR/Y17kdtfmzDztYFgJq91lE4DgoiAVibVc7gdX9pVAozUDIIZP1QRy/O1NgPNUy8thi1mM2vncpAVcYHAxvoCKQ7hWk+3OFPRo8k5hdYCnlusurqB/XfOzF9ZUuH6eejobLi9Q==,iv:mLOBVE8YpFJqgcLS7LTY8roHJrapWByvqRgW62H22Vw=,tag:+YbwPgKaaHV2itUrN7NXVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16vhmz79lvv4q7nes99c2mr2l5cmrq34qlnyws3dkfnhfa7jhapssqm2jkd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvaitOb3VmVU5WMHVxMGsv
            VmxtVTZCSHI3ZXFqTWVyZVF1aGtkTllCd3owClhwSU5JaU1udGtNYThUZVA2ZXFh
            VmZqS0h0M1RYdkh3d1ZBYTRmS3E0OUkKLS0tIE5TQXdBOHdnQ3lrZ0FmdENUN2Rj
            RUI5YncxMldFemNaTGhqTE5USFNmNkEKUsfSr62dTNsN/hvd0Mbsoln363wg4/hv
            Y+WrFagZ0oW95E2FFDz5DDfo8G5rh0c8fD1Jju7OyP14KkiU0Ez96A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-09T02:10:50Z"
    mac: ENC[AES256_GCM,data:UO+wBkuu5aZDJ95RcATCG1uARuVr/OAqjD66LlO6wfDnqbKP3XBL0R6pYtnBEOjuGxzYkVWWLoqDQN0NpwYFYzA3Lp/+n499CMu+czkg9L9K1u0jdCDw/BBAJ3Trers8cNDv3ryDQDXFkw4KXV8Yzr3y/0MVg6fydjIELoeMfBA=,iv:TTbQdMhydQsBqOfLNjV0VJiPjxsXLriQ5srEebiAhhw=,tag:9t4Icq1WuPAzFzb7WcOayQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
