---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app lidarr
  namespace: organizers
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/bh2754/lidarr-nightly
      tag: 1.5.0.3654@sha256:6ed533b3726452abc2952a0eb9f5a50d2a3f3a6e7c9be736bec034ec7ca2dc52
      pullPolicy: IfNotPresent
    env:
      TZ: ${TZ}
    envFrom:
      - secretRef:
        # name: *app
          name: lidarr-secret

    service:
      main:
        ports:
          http:
            port: 8686
    metrics:
      enabled: false
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        enabled: true
        existingClaim: lidarr-config-v1
      media:
        enabled: true
        type: nfs
        server: ${NFS_SERVER}
        path: ${NFS_MUSIC}
      downloads:
        enabled: true
        type: nfs
        server: ${NFS_SERVER}
        path: /volume1/Download
    ingress:
      main:
        enabled: true
        ingressClassName: "external"
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "lidarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    resources:
      requests:
        cpu: 10m
        memory: 1102M
        ephemeral-storage: "2Gi"
      limits:
        memory: 1428M
        ephemeral-storage: "4Gi"
    podAnnotations:
      setGateway: "true"
