---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-sabnzbd
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cluster-rook-ceph-cluster
    - name: cluster-apps-onepassword-connect
    - name: cluster-apps-pod-gateway
  path: ./kubernetes/apps/downloaders/sabnzbd/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: sabnzbd
      namespace: downloaders
  interval: 30m
  retryInterval: 1m
  timeout: 3m
